version: '3.7'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - TZ=UTC
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - 5601:5601
    environment:
      TZ: UTC
      ELASTICSEARCH_HOSTS: http://elastic:9200

  api:
    build:
      context: ./
    command: uvicorn main:app --port 3001 --host 0.0.0.0 --reload
    environment:
      TZ: UTC
      ELASTIC_HOST: http://elastic:9200
      APP_KEY: secret
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    depends_on:
      - elastic

  web:
    build:
      context: ./web
    command: yarn start
    environment:
      TZ: UTC
      PORT: 3000
      API_PROXY: http://api:3001/api/
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  elastic-data:
